Class02_hw2_Smart_Factory_최종_문정환
kgkorchamhrd/intel-01 pull request #161
Opened 2024-01-22 01:15 UTC by HardCoding0417

Class02_hw2_Smart_Factory_최종_문정환 #156

2024-01-22 03:37 UTC, J-WBaek requested changes
수정이 필요한 부분을 코멘트 달아 두었습니다.
확인해 보세요!

2024-01-22 03:37 UTC, J-WBaek commented on class02/homework/MoonJeangHwan/final/factory.py
> +
#160 
이 부부분에 inference 하는 방법 올려두었습니다. 참고해보세요.

2024-01-22 03:37 UTC, J-WBaek commented on class02/homework/MoonJeangHwan/final/factory.py
> +        q.put(('PUSH', 2))
if color == 'blue'
   q.put(('PUSH', 2))
로 처리해야 blue 병뚜껑이 detected 되었을 때 actuator 를 동작하게 할 수 있습니다.

2024-01-22 05:15 UTC, HardCoding0417 commented
코멘트 감사합니다! 오늘 8시 안에 수정해서 다시 올려보겠습니다.

2024-01-22 09:44 UTC, HardCoding0417 commented on class02/homework/MoonJeangHwan/final/factory.py
> +
말씀하신 부분을 참조해서 수정해보았습니다.

2024-01-29 02:05 UTC, J-WBaek approved these changes

2024-01-29 03:01 UTC, merged